input: 'D:\Desktop\Datasets\2019\early\agh-fis-spr17.xml'
steady_state: true
hyperparams:
  population_size: 512
  no_of_generations: 1000000000
  parent_selection: roulette
  mutation_chance: 0.005
  crossover_ratio: 0.3


