input: 'D:\Downloads\assignmentRedownload\instances\early\muni-fi-spr16.xml'
steady_state: true
hyperparams:
  population_size: 512
  no_of_generations: 1000000000
  parent_selection: roulette
  mutation_chance: 0.005
  crossover_ratio: 0.3


